ko/component-guide.md
Add deep learning instance component guide
=> Add deep learning instance

en/component-guide.md
Add translation for the following new contents:
- Deep Learning Framework
- JEUS, WebtoB
- Tomcat
- Node.js
=> Add English translation for 2021.11 release

ko/component-guide.md
=> Mysql 가이드 추가

en/component-guide.md
review completed for the source file '/ko/component-guide.md'
=> Add English translation of the MySQL section

en/component-guide.md
- Reflect update of Deep Learning Framework component
=> Add additional English translation for 2021.11

en/console-guide.md
- Improve parity with Console UI
=> Add English translation for console-guide.md

en/component-guide.md
- Add (restore) translation for Deep Learning Framework
- Modify expression for consistency
=> English translation and review for 2021.12 release

en/component-guide.md
- Translate the newly added Slurm section
=> Translate component guide (2022.01)

en/console-guide.md, en/overview.md
=> Translate overview and console guide (2022.01)

en/console-guide.md, en/overview.md
- Fix unclear or misleading translation
=> Improve translation on overview and console guide

ko/component-guide.md
=> Kafka image builder

en/component-guide.md
=> Translate update for Oct

zh/component-guide.md
kafka image builder manual -zh
=> kafka image builder manual -zh

en/component-guide.md
Translate content added for component guide
=> Translate update

ko/component-guide.md
=> MariaDB image bulider manual 수정 - ko

ko/component-guide.md
=> Revert MariaDB image bulider manual 수정 - ko

en/component-guide.md
=> MariaDB image bulider manual 수정 - en

ja/component-guide.md
=> MariaDB image bulider manual 수정 - ja

zh/component-guide.md
=> MariaDB image bulider manual 수정 - zh

en/component-guide.md, ja/component-guide.md, ko/component-guide.md, zh/component-guide.md
alpha -> beta (merge PR from alpha to beta)
=> MariaDB image bulider manual 수정

en/component-guide.md, ja/component-guide.md, ko/component-guide.md, zh/component-guide.md
apache_kafka_image_builder_manual
=> modify apache_kafka_image_builder_manual

en/component-guide.md, ja/component-guide.md, ko/component-guide.md, zh/component-guide.md
apache_kafka_image_builder_manual
=> apache_kafka_image_builder_manual

en/overview.md
=> Translate update for Mar

zh/overview.md
[tc-iaas-image-builder/155](https://nhnent.dooray.com/project/posts/3478264251051683870)
https://github.com/TOAST-DOCS/Compute-Image-Builder/pull/76 의 영문번역내용을 중문 가이드에 적용
=> 23-03-28 릴리즈 영문 번역 내용을 중문 가이드에 적용

en/component-guide.md
=> Translate update for Apr

en/component-guide.md
* Translate added
* Sync up w/ Ko
=> Translate update for May

ko/component-guide-gov.md, ko/component-guide.md
[#tc-iaas-image-builder/188](https://nhnent.dooray.com/project/posts/3671160880533921784)
=> 공공 사용자가이드에 NHN Kubernetes Service(NKS) Worker Node 추가

en/component-guide.md, ja/component-guide.md, ko/component-guide-gov.md, zh/component-guide.md
PostgreSQL 버전 문구 변경
13 -> ${version}
=> Beta -> Alpha Merge

en/component-guide.md, ja/component-guide.md, ko/component-guide.md, zh/component-guide.md
[Mgmt task](https://nhnent.dooray.com/task/2058408404193881826/3869103870524423332)
=> Fix: Change NHN Kubernetes Service(NKS) Worker Node's guide link

ko/component-guide-gov.md
[tc-qa-framework/8031](https://nhnent.dooray.com/project/tasks/3939949300604350561)
=> 컴포넌트 가이드 - NHN Kubernetes Service(NKS) Worker Node 가이드 링크 수정 (공공 반영) 
